name: 'aus_dbt_analytics'
version: '1.0.0'
config-version: 2

profile: 'aus_dbt_analytics'

model-paths: ["models"]
test-paths: ["tests"]
docs-paths: ["docs"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  aus_dbt_analytics:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
